services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python run.py
    volumes:
      - ./app:/usr/src/app/app
      - ./scripts:/usr/src/app/scripts
      - ./data:/usr/src/app/data
      - ./run.py:/usr/src/app/run.py
    ports:
      - "8010:8010"
    environment:
      APP_NAME: Nietzsche RAG Bot
      APP_ENV: development
      APP_HOST: 0.0.0.0
      APP_PORT: 8010
      DEBUG: "true"